[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo

# Admin master password - OVERRIDE en produccion via env o reemplazar este hash
admin_passwd = $pbkdf2-sha512$600000$1DpHCOHcu7dWKuV8T.k9Bw$xyiXMYCFYEynp.zP1X0ESWW0bHq0NIzPxYJn/WDjiPK1B8MP9pOA5oCr5IGHb7Jm/2xPbQlAJK.gWlAI9kll4Q

# Database connection
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_maxconn = 32

# Worker / limits (ajustar segun specs del VPS)
workers = 0
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_request = 8192
limit_time_cpu = 600
limit_time_real = 1200

# Logs
log_level = info
log_handler = :INFO

# HTTP / proxy
proxy_mode = True
# longpolling_port = 8072  # Odoo 17 - configurado via gevent_port

# SMTP - reemplazar en produccion. En dev apunta a MailHog.
smtp_server = mailhog
smtp_port = 1025
smtp_ssl = False
email_from = noreply@indigodecors.local

# Demo data
without_demo = False

# Misc
list_db = True
