# -*- coding: utf-8 -*-
{
    'name': 'Indigo Decors',
    'version': '17.0.0.16.0',
    'category': 'Manufacturing',
    'summary': 'Gestion de ordenes de puertas decorativas',
    'description': """
Indigo Decors — Gestion de ordenes
==================================
Modulo a medida para el taller Indigo Decors:
ordenes multi-pieza, pipeline kanban configurable por dealer,
documentos (ficha de orden, etiqueta del disenador, hoja del pintor),
liquidacion de contratistas (pintor por SQF, instaladores por puerta)
y portal externo para instaladores.
""",
    'author': 'Indigo Decors',
    'website': 'https://www.indigodecors.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'mail',
        'web',
        'product',
        'account',
        'portal',
        'sale_management',
        'website_sale',
    ],
    'data': [
        'security/indigo_security.xml',
        'security/ir.model.access.csv',
        'security/indigo_portal_rules.xml',
        'data/indigo_sequence.xml',
        'data/indigo_stages.xml',
        'data/mail_templates.xml',
        'data/demo_dealers.xml',
        'data/demo_designs.xml',
        'data/demo_rates.xml',
        'data/demo_direct_sales.xml',
        'data/cron_sla.xml',
        'data/cron_stock.xml',
        'views/indigo_menu_root.xml',
        'views/indigo_stage_views.xml',
        'views/indigo_design_views.xml',
        'views/indigo_dealer_views.xml',
        'views/indigo_order_views.xml',
        'views/indigo_order_kanban.xml',
        'views/indigo_order_calendar.xml',
        'views/indigo_payout_views.xml',
        'views/indigo_contractor_rate_views.xml',
        'views/indigo_stock_views.xml',
        'views/product_template_indigo_views.xml',
        'views/sale_order_views.xml',
        'views/indigo_menus.xml',
        'views/portal_templates.xml',
        'wizards/indigo_order_bulk_assign_wizard_views.xml',
        'reports/paperformats.xml',
        'reports/order_card_report.xml',
        'reports/order_label_report.xml',
        'reports/painter_sheet_report.xml',
        'reports/installation_addresses_report.xml',
        'reports/payout_report.xml',
        'wizards/indigo_payout_settle_wizard_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    # i18n: fuente es_ES, traduccion ingles en i18n/en.po (parcial ~50%).
}
